ALTER TABLE public.parfums DROP CONSTRAINT IF EXISTS parfums_sale_mode_check;
ALTER TABLE public.parfums ADD CONSTRAINT parfums_sale_mode_check
  CHECK (sale_mode IN ('decant', 'full_bottle', 'decant_full'));

DELETE FROM public.parfums;

INSERT INTO public.parfums
  (name, maison, gender, description, notes_tete, notes_coeur, notes_fond,
   price_5ml, price_10ml, price_20ml, image_label, is_new, is_bestseller,
   sale_mode, full_bottle_volume_ml, full_bottle_price, full_bottle_stock,
   is_active, stock_status)
VALUES
  ('Stronger With You Absolutely','Giorgio Armani','Homme'::parfum_gender,'Un élixir vibrant et addictif, où la fève tonka rencontre des accords ambrés profonds.',ARRAY['Cardamome','Note verte']::text[],ARRAY['Fève tonka','Rhum']::text[],ARRAY['Vanille','Bois de santal']::text[],0,65,110,'stronger-with-you-absolutely',false,true,'decant_full',100,140,12,true,'actif'::stock_status),
  ('Stronger With You Intensely','Giorgio Armani','Homme'::parfum_gender,'Une signature chaleureuse et gourmande, taillée pour les soirées d''hiver.',ARRAY['Sauge','Lavande','Cardamome verte']::text[],ARRAY['Fève tonka','Cannelle']::text[],ARRAY['Vanille','Caramel','Ambre']::text[],0,60,105,'stronger-with-you-intensely',false,true,'decant_full',100,130,12,true,'actif'::stock_status),
  ('Turathi Electric','Afnan','Homme'::parfum_gender,'Un boisé aromatique électrique, moderne et facile à porter au quotidien.',ARRAY['Pomme','Bergamote']::text[],ARRAY['Lavande','Iris']::text[],ARRAY['Ambre','Musc','Bois']::text[],0,40,70,'turathi-electric',true,false,'decant_full',100,90,12,true,'actif'::stock_status),
  ('Rare Reef','Afnan','Mixte'::parfum_gender,'Une fraîcheur marine lumineuse, idéale pour le printemps et l''été.',ARRAY['Agrumes','Note marine']::text[],ARRAY['Jasmin','Note aquatique']::text[],ARRAY['Ambre gris','Musc']::text[],0,35,65,'rare-reef',true,false,'decant_full',100,80,12,true,'actif'::stock_status),
  ('9PM Night Out','Afnan','Mixte'::parfum_gender,'La version nocturne du 9PM : plus fruitée, plus sucrée, très sillage.',ARRAY['Fruits rouges','Bergamote']::text[],ARRAY['Cannelle','Fleur d''oranger']::text[],ARRAY['Vanille','Ambre','Musc']::text[],0,35,65,'9pm-night-out',true,true,'decant_full',100,80,12,true,'actif'::stock_status),
  ('9 PM','Afnan','Homme'::parfum_gender,'Le best-seller absolu : gourmand, ambré et redoutablement efficace le soir.',ARRAY['Pomme','Cannelle','Lavande']::text[],ARRAY['Fève tonka','Iris']::text[],ARRAY['Vanille','Ambre','Musc']::text[],0,35,65,'9-pm',false,true,'decant_full',100,80,12,true,'actif'::stock_status),
  ('9 PM Elixir','Afnan','Homme'::parfum_gender,'Une concentration plus dense et plus sombre du 9PM, pensée pour l''hiver.',ARRAY['Épices','Fruits secs']::text[],ARRAY['Fève tonka','Cacao']::text[],ARRAY['Vanille','Ambre','Bois']::text[],0,40,70,'9-pm-elixir',true,true,'decant_full',100,90,12,true,'actif'::stock_status),
  ('9 PM Rebel','Afnan','Homme'::parfum_gender,'Un caractère plus frais et plus insolent, portable du matin au soir.',ARRAY['Agrumes','Épices fraîches']::text[],ARRAY['Lavande','Géranium']::text[],ARRAY['Bois de santal','Musc','Ambre']::text[],0,35,65,'9-pm-rebel',true,false,'decant_full',100,80,12,true,'actif'::stock_status),
  ('French Tobacco','Ibrahim Al Qurashi','Homme'::parfum_gender,'Un tabac miellé enveloppant, chaud et élégant.',ARRAY['Épices','Bergamote']::text[],ARRAY['Tabac','Miel']::text[],ARRAY['Vanille','Fève tonka','Bois']::text[],0,35,65,'french-tobacco',false,true,'decant_full',100,80,12,true,'actif'::stock_status),
  ('Y Eau de Parfum','Yves Saint Laurent','Homme'::parfum_gender,'L''épure moderne : frais en tête, boisé et minéral en fond.',ARRAY['Pomme','Gingembre','Bergamote']::text[],ARRAY['Sauge sclarée','Géranium']::text[],ARRAY['Fève tonka','Cèdre','Encens']::text[],0,60,110,'y-eau-de-parfum',false,true,'decant_full',100,135,12,true,'actif'::stock_status),
  ('Valentino Born In Roma Intense','Valentino','Homme'::parfum_gender,'Une élégance italienne assumée : violette et bois pour un sillage habillé.',ARRAY['Sauge','Lavande']::text[],ARRAY['Violette','Encens']::text[],ARRAY['Vétiver','Bois','Ambre']::text[],0,65,110,'valentino-born-in-roma-intense',false,true,'decant_full',100,140,12,true,'actif'::stock_status),
  ('Hawas Kobra','Rasasi','Homme'::parfum_gender,'Un frais-fruité puissant, très performant sous la chaleur marocaine.',ARRAY['Ananas','Bergamote','Poivre']::text[],ARRAY['Note marine','Cannelle']::text[],ARRAY['Ambre gris','Musc','Bois']::text[],0,40,70,'hawas-kobra',true,true,'decant_full',100,90,12,true,'actif'::stock_status),
  ('Le Beau Le Parfum','Jean Paul Gaultier','Homme'::parfum_gender,'Un solaire boisé lacté, à la fois doux et magnétique.',ARRAY['Bergamote','Coco']::text[],ARRAY['Note verte','Figue']::text[],ARRAY['Bois de santal','Tonka']::text[],0,60,110,'le-beau-le-parfum',false,true,'decant_full',100,135,12,true,'actif'::stock_status),
  ('Le Beau Paradise Garden','Jean Paul Gaultier','Homme'::parfum_gender,'Une escapade tropicale : fruits solaires et bois crémeux.',ARRAY['Ananas','Bergamote']::text[],ARRAY['Ylang-ylang','Coco']::text[],ARRAY['Bois de santal','Vanille']::text[],0,60,110,'le-beau-paradise-garden',true,true,'decant_full',100,135,12,true,'actif'::stock_status),
  ('Light Blue Eau de Toilette','Dolce & Gabbana','Femme'::parfum_gender,'Le frais méditerranéen intemporel, parfait pour les journées ensoleillées.',ARRAY['Citron de Sicile','Pomme Granny']::text[],ARRAY['Jasmin','Rose blanche','Bambou']::text[],ARRAY['Cèdre','Ambre','Musc']::text[],0,45,80,'light-blue-eau-de-toilette',false,true,'decant_full',100,100,12,true,'actif'::stock_status),
  ('Pink Diamond Sakura','Ibrahim Al Qurashi','Femme'::parfum_gender,'Un floral rosé délicat et lumineux, très facile à porter.',ARRAY['Fleur de cerisier','Litchi']::text[],ARRAY['Pivoine','Rose']::text[],ARRAY['Musc blanc','Vanille']::text[],0,35,65,'pink-diamond-sakura',true,false,'decant_full',100,80,12,true,'actif'::stock_status),
  ('Burberry Her Eau de Parfum','Burberry','Femme'::parfum_gender,'Un fruité-gourmand couture, moderne et enveloppant.',ARRAY['Fruits rouges','Mandarine']::text[],ARRAY['Jasmin','Violette']::text[],ARRAY['Musc','Bois de santal','Vanille']::text[],0,70,125,'burberry-her-eau-de-parfum',false,true,'decant_full',100,155,12,true,'actif'::stock_status),
  ('Prada Paradox Eau de Parfum','Prada','Femme'::parfum_gender,'Un floral musqué contrasté : frais en ouverture, cocooning en fond.',ARRAY['Bergamote','Néroli']::text[],ARRAY['Fleur d''oranger','Jasmin']::text[],ARRAY['Musc','Ambre','Bois']::text[],0,70,130,'prada-paradox-eau-de-parfum',false,true,'decant_full',100,160,12,true,'actif'::stock_status),
  ('Old Spice Captain (Déodorant Stick)','Old Spice','Homme'::parfum_gender,'Déodorant stick longue tenue, sillage boisé marin.','{}'::text[],'{}'::text[],'{}'::text[],0,0,0,'old-spice-captain',false,false,'full_bottle',50,90,12,true,'actif'::stock_status),
  ('Old Spice Wolfthorn (Déodorant Stick)','Old Spice','Homme'::parfum_gender,'Déodorant stick longue tenue, sillage fruité épicé.','{}'::text[],'{}'::text[],'{}'::text[],0,0,0,'old-spice-wolfthorn',false,false,'full_bottle',50,90,12,true,'actif'::stock_status),
  ('Pack Burberry Her EDP + Light Blue EDT','Tabat','Femme'::parfum_gender,'Duo féminin : le fruité-gourmand de Burberry Her et la fraîcheur de Light Blue.','{}'::text[],'{}'::text[],'{}'::text[],0,0,0,'pack-burberry-her-light-blue',false,true,'full_bottle',200,230,12,true,'actif'::stock_status),
  ('Pack Burberry Her EDP + Light Blue EDT + Prada Paradox EDP','Tabat','Femme'::parfum_gender,'Trio féminin complet : gourmand, frais et floral musqué.','{}'::text[],'{}'::text[],'{}'::text[],0,0,0,'pack-burberry-light-blue-paradox',false,true,'full_bottle',300,310,12,true,'actif'::stock_status),
  ('Pack Paradise Garden + Le Beau Le Parfum + Hawas Kobra','Tabat','Homme'::parfum_gender,'Trio masculin solaire : deux Gaultier et le puissant Hawas Kobra.','{}'::text[],'{}'::text[],'{}'::text[],0,0,0,'pack-paradise-garden-le-beau-hawas',false,true,'full_bottle',300,235,12,true,'actif'::stock_status),
  ('Pack French Tobacco + Y EDP + Déodorant Old Spice','Tabat','Homme'::parfum_gender,'Coffret complet : un tabac miellé, un boisé frais et un déodorant stick.','{}'::text[],'{}'::text[],'{}'::text[],0,0,0,'pack-french-tobacco-y-old-spice',false,true,'full_bottle',250,270,12,true,'actif'::stock_status);

UPDATE public.app_settings SET bot_name = 'Assistante Tabat' WHERE bot_name = 'Assistante Myaura';